### ISSUE TITLE
File->open for Cinema database

### ISSUE THREAD

**Issue by dhrogers** [cinemascience/cinema_scope#3]
Implement file->open for the application. The application should filter for *.cdb directories and open those in the application.

**Comment by terryturton** [comment]
As a corollary, can it be implemented such that a user could select one of multiple FILE* columns to view, if more than one FILE column exists?  
I am thinking of cinema_lib functions that create additional FILE columns.  In order to view a new FILE column with cinema_compare or cinema_scope, the user would need to edit data.csv to reorder the FILE columns.

**Comment by dhrogers** [comment]
Sure we can do that as our first feature add.

**Comment by dhrogers** [comment]
Complete. Design should be cleaned up as part of other issues (request to make separate classes, etc.)
